openapi: 3.0.3
info:
  title: Authentication API
  version: 1.0.0
servers:
  - url: http://localhost/api
paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - first_name
                - last_name
                - email
                - password
                - type
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 6
                type:
                  type: string
                  enum:
                    - APPROVER
                    - NON_APPROVER
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  token:
                    type: string
        '401':
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  errors:
                    type: object

  /auth/login:
    post:
      summary: Log in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  token:
                    type: string
        '401':
          description: Validation error or email and password do not match
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  errors:
                    type: object

  /report/earnings:
    get:
      summary: Get earnings report
      description: Returns the earnings report, including total earnings per month and year for approved jobs.
      operationId: getEarningsReport
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Earnings report successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    year:
                      type: integer
                      example: 2022
                    month:
                      type: integer
                      example: 5
                    total_earnings:
                      type: number
                      example: 4500.00
        '401':
          description: Unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
